mode: rule
log-level: info
allow-lan: false
ipv6: true
# --- DNS 设置 ---
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.28.28.28
    - system
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - stun.*
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - music.163.com
    - '*.music.163.com'
    - y.qq.com
    - '*.y.qq.com'
    - xbox.*.microsoft.com
    - '*.*.xboxlive.com'
    - '*.srv.nintendo.net'
    - '*.cmpassport.com'

# --- 订阅设置 ---
proxy-providers:
  cloudflare:
    type: http
    url: 
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
    benchmark-url: http://www.gstatic.com/generate_204

#节点
proxies:
  - name: 直连
    type: DIRECT
    udp: true

#策略组
proxy-groups:
  - name: 节点选择
    type: select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Area.png
    proxies: [自动选择, 直连, 港台节点, 日韩节点, 新加坡节点, 美国节点, 欧洲节点, 谷歌云]
  - filter: 谷歌云
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/iCloud.png
    include-all: true
    name: 谷歌云
    type: select
  - name: Google
    type: select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
    proxies: [节点选择, 谷歌云, 美国节点, 美国优选, 日韩节点, 新加坡节点]
  - name: YouTube
    type: select
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png
    proxies: [节点选择, 美国节点, 美国优选, 日韩节点, 新加坡节点, 欧洲节点]
  - name: Telegram
    type: select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    proxies: [节点选择, 谷歌云, 日韩节点, 新加坡节点, 美国节点, 欧洲节点]
  - name: 国际媒体
    type: select
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ForeignMedia.png
    proxies: [节点选择, 谷歌云, 日韩节点, 新加坡节点, 美国节点, 欧洲节点]
  - name: OPENAI
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bot.png
    type: select
    proxies: [谷歌云, 美国节点, 美国优选, 日韩节点, 新加坡节点, 节点选择]
  - name: Github
    icon: 'https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/GitHub.png'
    type: select
    proxies: [节点选择, 谷歌云, 日韩节点, 新加坡节点, 美国节点, 欧洲节点, 自动选择, 直连]
  - name: 国内直连
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/DomesticMedia.png
    type: select
    proxies: [直连, 节点选择, 日韩节点, 港台节点, 自动选择]
  - name: 兜底分流
    type: select
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Final.png
    proxies: [节点选择, 新加坡节点, 美国节点, 欧洲节点, 自动选择, 直连]
  - name: 自动选择
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Auto.png
    type: url-test
    include-all: true
    exclude-type: direct
    tolerance: 10
    filter: "^((?!(直连)).)*$"

  #分隔,下面是地区分组
  - name: 美国节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png
    type: url-test
    include-all: true
    exclude-type: direct
    filter: "(?i)美|us|unitedstates|united states"
  - name: 美国优选
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/US.png
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)美|us|unitedstates|united states"
  - name: 新加坡节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png
    type: url-test
    include-all: true
    exclude-type: direct
    filter: "(?i)(新|sg|singapore)"
  - name: 港台节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png
    type: url-test
    include-all: true
    exclude-type: direct
    filter: "(?i)港|hk|hongkong|hong kong|(?i)台|tw|taiwan"
  - name: 日韩节点
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png
    type: load-balance
    include-all: true
    exclude-type: direct
    filter: "日|🇯🇵|东京|JP|(?i)Japan|韩|🇰🇷|首尔|KR|(?i)Korea"
  - name: 欧洲节点
    icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/EU.png
    type: url-test
    include-all: true
    exclude-type: direct
    filter: '英国|🇬🇧|UK|GB|德国|🇩🇪|DE|法国|🇫🇷|FR|荷兰|🇳🇱|NL|PL|波兰|🇵🇱'
rules:
  - SCRIPT,quic,REJECT
  - RULE-SET,Reject,Reject
  - DOMAIN-SUFFIX,993011.xyz,直连
  - DOMAIN-SUFFIX,992105.xyz,直连
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,private_domain,直连
  - RULE-SET,paypal,Google
  - RULE-SET,openai_domain,OPENAI
  - RULE-SET,github_domain,Github
  - RULE-SET,twitter_domain,国际媒体
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,netflix_domain,国际媒体
  - RULE-SET,biliintl_domain,国际媒体
  - RULE-SET,bilibili_domain,国内直连
  - RULE-SET,reddit_domain,国际媒体
  - RULE-SET,spotify_domain,国际媒体
  - RULE-SET,tiktok_domain,国际媒体
  - RULE-SET,pixiv_domain,国际媒体
  - RULE-SET,gfw_domain,国际媒体
  - RULE-SET,cn_domain,国内直连
  - RULE-SET,cloudflare_domain,国际媒体
  - RULE-SET,geolocation-!cn,兜底分流
  - RULE-SET,google_ip,Google
  - RULE-SET,netflix_ip,国际媒体
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,twitter_ip,国际媒体
  - RULE-SET,cn_ip,国内直连
  - RULE-SET,cloudflare_ip,国际媒体
  - MATCH,兜底分流
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
  yaml: &yaml {type: http, interval: 86400, behavior: classical, format: yaml}
rule-providers:
  private_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml"
  cn_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
  biliintl_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.yaml"
  github_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml"
  twitter_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.yaml"
  youtube_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml"
  google_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml"
  telegram_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml"
  netflix_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml"
  bilibili_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.yaml"
  openai_domain:
    !!merge <<: *domain
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.yaml"
  reddit_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/reddit.yaml"
  spotify_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.yaml"
  tiktok_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.yaml"
  pixiv_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.yaml"
  cloudflare_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.yaml"
  gfw_domain:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.yaml"
  geolocation-!cn:
    !!merge <<: *domain
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml"
  private_ip:
    !!merge <<: *ip
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml"
  cn_ip:
    !!merge <<: *ip
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml"
  google_ip:
    !!merge <<: *ip
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml"
  netflix_ip:
    !!merge <<: *ip
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.yaml"
  twitter_ip:
    !!merge <<: *ip
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.yaml"
  telegram_ip:
    !!merge <<: *ip
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml"
  cloudflare_ip:
    !!merge <<: *ip
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudflare.yaml"
  Reject:
    !!merge <<: *yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml"
  paypal:
    !!merge <<: *yaml
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml"
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
http:
  url-rewrite:
    - '^https?://(www.)?google.cn https://www.google.com 302'
    - '^https?://(www.)?g.cn https://www.google.com 302'
    - '^https?://(www.)?google.cn/search https://www.google.com/search 302'
    - 'https://www.google.cn https://www.google.com 302'
    - 'http://‎google.cn https://www.google.com 302'
